@extends('layouts.policies')
@section('policy')
<h3>RAYVR User Terms and Conditions</h3>
<p>These Terms of Service ("Terms") govern your access to and use of the services and RAYVR's websites (the "Services"), and any information, text, graphics, or other materials uploaded, downloaded or appearing on the Services (collectively referred to as "Content"). Your access to and use of the Services is conditioned on your acceptance of and compliance with these Terms. By accessing or using the Services you agree to be bound by these Terms.</p><br>
<p class="h5">Basic Terms</p>
<p>You are responsible for your use of the Services, for any content you post to or as a result of the Services, verifying your website stats, posting content to the same url you apply to a promotion with, complying with FTC regulations on all posts you make, and for any consequences thereof. The Content you submit, post, or display will be able to be viewed by other users of the Services and through third party services and websites. You should only provide Content that you are comfortable sharing with others under these Terms.</p><br>
<p>You may use the Services only if you can form a binding contract with RAYVR and are not a person barred from receiving services under the laws of the United States or other applicable jurisdiction. You may use the Services only in compliance with these Terms and all applicable local, state, national, and international laws, rules and regulations.</p><br>
<p>The Services that RAYVR provides are always evolving and the form and nature of the Services that RAYVR provides may change from time to time without prior notice to you. In addition, RAYVR may stop (permanently or temporarily) providing the Services (or any features within the Services) to you or to users generally and may not be able to provide you with prior notice. We also retain the right to create limits on use and storage at our sole discretion at any time without prior notice to you.</p><br>
<p>The Services may include advertisements, which may be targeted to the Content or information on the Services, queries made through the Services, or other information. The types and extent of advertising by RAYVR on the Services are subject to change. In consideration for RAYVR granting you access to and use of the Services, you agree that RAYVR and its third party providers and partners may place such advertising on the Services or in connection with the display of Content or information from the Services whether submitted by you or others.</p><br>
<p>RAYVR does NOT endorse any of the products listed on RAYVR.  All products and services are the responsibility of the company listing the product and any RAYVR members using the product or service are doing so at their own risk.</p><br>
<p class="h5">Privacy</p>
<p>Our goal is to make the Program as good, useful and rewarding for you as possible. In order to do that, we need to collect and process information from you when you use the Program. We will collect certain personally identifiable information from you as set forth in more detail in our Privacy Policy {{ HTML::link('https://rayvr.com/resources/privacy', 'https://rayvr.com/resources/privacy', ['target' => '_blank']) }}, which is part of the Terms. When you use the Program, RAYVR has access to, and in many cases will monitor, your usage of the Program as you send and receive Content (defined below). By accessing and using the Program, you agree that we may collect, use and disclose, as set forth in the Privacy Policy, certain information you provide during your access to or use of the Program, and in some cases information that is provided to the Program by other parties. As part of providing you the Program, we may need to provide you with certain infrequent service communications, such as service announcements and administrative messages ("Service Communications"). These Service Communications, which will not include advertisements, are considered part of the Services and your Account, which you may not be able to opt­out from receiving.</p><br>
<p class="h5">Your Account</p>
<p>You may only create and hold one account on the Site for your personal use. You are responsible for updating and correcting information you have submitted to create or maintain your account. As part of your account settings, you have the option to: (a) save, edit or delete your personal information, including, without limitation; and (b) opt­out of persistent login. You understand and agree that RAYVR shall have no responsibility for any incident arising out of, or related to, your account settings. You must safeguard your password and supervise the use of your account. You are solely responsible for maintaining the security of your account and maintaining settings that reflect your preferences. We will assume that anyone using the Site or transacting through your account is you. You agree that you are solely responsible for any activity that occurs under your account. Your account will expire and you will lose any RAYVR points earned through a Promotional Activity if your account is not maintained with current information.</p><br>
<p>Your account is non­transferrable. You cannot sell, combine, or otherwise share it with any other person.</p><br>
<p>Any violation of these Terms of Use, including failure to maintain updated and correct information about your account, will cause your account to fall out of good standing and we may cancel your account in our sole discretion. If your account is cancelled, you may forfeit any pending, current or future promotional account credits and any other forms of unredeemed value in your account. Upon termination, the provisions of these Terms of Use that are by their nature intended to survive termination (e.g., any disclaimers, all limitations of liability and all indemnities) shall survive. We also reserve the right to change or discontinue any aspect or feature of our services or the Site, including, but not limited to, requirements for use.</p><br>
<p class="h5">Passwords</p>
<p>You are responsible for safeguarding the password that you use to access the Services and for any activities or actions under your password. We encourage you to use "strong" passwords (passwords that use a combination of upper and lower case letters, numbers and symbols) with your account. RAYVR cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements.</p><br>
<p class="h5">Links</p>
<p>The Services may contain links to third­party websites or resources. You acknowledge and agree that we are not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by RAYVR of such websites or resources or the content, products, or services available from such websites or resources. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources.</p><br>
<p class="h5">Messaging</p>
<p>As part of the Services we provide, you may receive emails or other types of messages directly sent to you outside our website. You have control over the Push Messages settings, and can opt in or out of these emails through the Services or through the phone's operating system (with the possible exception of infrequent, important service announcements and administrative messages).</p><br>
<p>We may offer you the opportunity to invite your friends or contacts to join RAYVR and enjoy the Services.</p>
If you click to invite one or more of your friends or contacts, we may suggest content for the message.</p><br>
<p>You can edit that suggested content if you do choose to send such invitations, you represent to RAYVR that the recipients of such invitations have consented to receive such messages from you, and that those recipients do not consider such messages unwanted or unsolicited.</p><br>
<p class="h5">Shipping Reimbursements</p>
<p>When you redeem an offer provided to you by RAYVR, it is your responsibility to return to {{ HTML::link('https://rayvr.com', 'RAYVR.com') }} and enter the order confirmation number and EXACT amount you paid for shipping. Users will only be reimbursed for standard shipping. You will be reimbursed for shipping costs via PayPal within 48 hours of redeeming the offer, pending approval. If the shipping claims are disputed, RAYVR customer service will contact you to ask for a copy of the receipt. RAYVR reserves the right to terminate any user who falsifies shipping amounts.</p><br>
<p class="h5">One Account per User</p>
<p>RAYVR users may only set up one account. We reserve the right to ask you to validate your account via SMS or by mail to verify your identity.</p><br>
<p class="h5">Account Suspension for Inactivity</p>
WE MAY DEEM YOUR ACCOUNT INACTIVE IF YOU HAVE NOT ACTIVELY USED THE APPLICATION FOR 30 DAYS OR MORE. RAYVR MAY SUSPEND YOUR ACCOUNT  AT ANY TIME, WITHOUT NOTICE AND AT RAYVR'S SOLE DISCRETION.</p><br>
<p class="h5">Payment</p>
<p>The use of the Services and Applications is currently made available to users free of charge; however, while it is not currently intended, we reserve the right to charge a fee for using the Services at any time. If we begin charging a fee for your continued access to the Services, we will give you at least 15 days prior notice so you can opt out of the Services. If you choose to opt out of the Services, RAYVR may forfeit any or all points, Bonuses and/or other awards in your Account after the prior notice period.</p><br>
<p class="h5">Content</p>
<p>Certain portions of the Program may allow you to post or upload text, graphics, images, and other content for display or publication through the Services ("Content"). By submitting Content to RAYVR, you hereby grant RAYVR a worldwide, royalty­free, sublicense­able and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the Content in connection with the Services and RAYVR's (and its successor's) business, including without limitation for promoting and redistributing part or all of the Program (and derivative works thereof) in any media formats and through any media channels. If you publish images or other such content through the Services, they may be viewed by and shared with other users, for example, on social networks like Facebook, based on your settings.</p><br>
<p>You agree not to: (i) submit material that violates anyone else's proprietary rights, including privacy and publicity rights, or can be considered spam or junk mail; (ii) knowingly publish false or inaccurate information; (iii) submit material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate; (iv) post advertisements, "pyramid schemes," chain letters or other solicitations; or (v) impersonate another person. RAYVR does not endorse any Content or any opinion, recommendation, or advice expressed therein, and we expressly disclaim any and all liability in connection with any Content. We reserve the right to decide whether Content is appropriate and complies with the Terms, and may remove such Content and/or terminate your access for uploading material in violation of the Terms at any time without prior notice. We will fully cooperate with any law enforcement authorities or court order requesting or directing us to disclose the identity of anyone posting publishing or otherwise making available Content or other materials that are believed to violate the Terms.</p><br>
<p>It is RAYVR's policy to terminate your access to the Services if you infringe the copyright rights of others upon receipt of proper notification to RAYVR by the copyright owner or the copyright owner's legal agent.</p><br>
<p>Without limiting the foregoing, if you believe that your work has been copied and posted on the Services in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: (i) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (ii) a description of the copyrighted work that you claim has been infringed; (iii) a description of where the material that you claim is infringing is located on the Services; (iv) your address, telephone number, and email address; (v) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; (vi) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. You may contact our Copyright Agent through {{ HTML::link('https://rayvr.com/contact', 'our support form') }}.</p><br>
<p class="h5">Restrictions</p>
<p>The Program may be used and accessed for lawful purposes only. You agree not to, and to not encourage or conspire with anyone else to, engage in any conduct that is inconsistent with the purposes, intent and spirit of the Program, or otherwise "game the system". You also agree to abide by all applicable local, state, national and foreign laws and regulations in connection with your use of the Services. In addition, you agree not to do any of the following:
	<ul>
		<li>Submitting any content to the Site that:
			<ul>
				<li>Violates applicable laws (including but not limited to intellectual property laws, laws relating to rights of privacy and rights of publicity and laws related to defamation);</li>
				<li>Contains personal information, except when we expressly ask you to provide such information;</li>
				<li>Contains viruses or malware;</li>
				<li>Offers unauthorized downloads of any copyrighted, confidential or private information;</li>
				<li>Has the effect of impersonating others;</li>
				<li>Contains messages by non­spokesperson employees of RAYVR purporting to speak on behalf of RAYVR or provides confidential information concerning RAYVR;<li>
				<li>Contains chain letters of any kind;</li>
				<li>Is purposely inaccurate, commits fraud or falsifies information in connection with your RAYVR account or to create multiple RAYVR accounts; or</li>
				<li>Is protected by copyright, trademark or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right.</li>
			</ul>
		</li>
		<li>Attempting to do or actually doing any of the following:
			<ul>
				<li>Accessing data not intended for you, such as logging into a server or an account which you are not authorized to access;<li>Scanning or monitoring the Site for data gathering purposes in an effort to track sales, usage, aggregate offering information, pricing information or similar data;</li>
				<li>Scanning or testing the security or configuration of the Site or to breach security or authentication measures; or</li>
				<li>Interfering with service to any user in any manner, including, without limitation, by means of submitting a virus to the Site or attempting to overload, "flood," "spam," "mail bomb" or "crash" the Site.</li>
			</ul>
		</li>
		<li>Using any of the following:
			<ul>
				<li>Frames, framing techniques or framing technology to enclose any content included on the Site without our express written permission;</li>
				<li>Any Site content, including without limitation User Content (defined below), in any meta tags or any other "hidden text" techniques or technologies without our express written permission;</li>
				<li>The Site or any of its contents to advertise or solicit, for any commercial, political or religious purpose or to compete, directly or indirectly, with RAYVR; or</li>
				<li>The Site or any of its resources to solicit consumers, Businesses or other third­parties to become users or partners of other online or offline services directly or indirectly competitive or potentially competitive with RAYVR, including, without limitation, aggregating current or previously offered deals. ·    Collecting any of the following:
					<ul>
						<li>Content from the Site, including, but not limited to, in connection with current or previously offered deals, and featuring such content to consumers in any manner that diverts traffic from the Site without our express written permission; or</li>
						<li>Personal Information (defined in our Privacy Statement), User Content (defined in Section 12 below) or content of any consumers or Businesses.</li>
					</ul>
				</li>
			</ul>
		</li>
		<li>Engaging in any of the following:
			<ul>
				<li>Tampering or interfering with the proper functioning of any part, page or area of the Site or any functions or services provided by RAYVR;</li>
				<li>Taking any action that places excessive demand on our services or imposes, or may impose, an unreasonable or disproportionately large load on our servers or other portion of our infrastructure (as determined in our sole discretion);</li>
				<li>Reselling or repurposing your access to the Site or any purchases made through the Site;</li>
				<li>Exceeding or attempting to redeem the same offer more than once or otherwise using any RAYVR offers for resale or for speculative, false, fraudulent or any other purpose not expresspressly permitted by these Terms of Use and the terms of a specific offer on the Site;</li>
				<li>Accessing, monitoring or copying any content from the Site using any "robot," "spider," "scraper" or other automated means or any manual process for any purpose without our express written permission;</li>
				<li>Violating the restrictions in any robot exclusion headers on the Site or bypassing or circumventing other measures employed to prevent or limit access to the Site;</li>
				<li>Aggregating any current or previously­offered deals or content or other information from the Site (whether using links or other technical means or physical records associated with purchases made through the Site) with material from other sites or on a secondary site without our express written permission;</li>
				<li>Deep­linking to any portion of the Site (including, without limitation, the purchase path for any Voucher) without our express written permission;</li>
				<li>Hyperlinking to the Site from any other website without our initial and ongoing consent; or</li>
				<li>Acting illegally or maliciously against the business interests or reputation of RAYVR, our Businesses or our services.</li>
			</ul>
		</li>
	</ul>
</p><br>
<p>RAYVR expressly reserves the right to retroactively reverse any rewards or benefits granted to you for any such prohibited conduct, or based on any material violation of the Terms; you agree to provide your full cooperation and prompt repayment under such circumstances. RAYVR shall determine, in its sole discretion, whether you have engaged in prohibited conduct; RAYVR's determination shall be final and unreviewable, and you waive any and all rights you may have to challenge that decision.</p><br>
<p class="h5">Termination; Cancellation</p>
<p>You may terminate your Account at any time and for any reason by deleting your account via the Application or by sending RAYVR an email notice with the subject line "please cancel my RAYVR membership" to support@RAYVR.com and requesting to be removed from the program. By canceling your RAYVR membership, the account registered to you will be terminated and may no longer be accessible, and all points will be immediately forfeited. Any termination request will be handled within 30 days of receipt of such a request by RAYVR. Any suspension, termination or cancellation will not affect your obligations to RAYVR under the Terms (including but not limited to ownership, indemnification and limitation of liability), which by their sense and context are intended to survive such suspension, termination or cancellation.</p><br>
<p>We may immediately terminate your Account or suspend your access to the Services and remove any material (including any Content provided by you) from the Services or our servers, in the event that you breach the Terms or for other improper conduct, at our sole discretion and without prior notice to you. As a result of any such termination, we may disqualify you from future participation in our programs and services. We also reserve the right to terminate your Account or or suspend your access to the Services at any time and for any reason, including but not limited to the need to conduct maintenance or if we discontinue any portion of the Services.</p><br>
<p>Upon termination, all licenses and other rights granted to you under the Terms will immediately cease, and you will forfeit all points, bonuses and other awards accrued. We will not be liable to you or any other person for termination of your Account or suspension of your access to the Services. Upon any termination or suspension, any information (including Content) that you have submitted to the Services may no longer be accessed by you. Furthermore, we will have no obligation to maintain any information stored in our database related to your Account or to forward any information to you or any other person.</p><br>
<p class="h5">Ownership</p>
<p>The Services and Application are protected by copyright, trademark, and other laws of the United States and foreign countries. RAYVR and its licensors exclusively own all right, title and interest in and to the Services and Application, including all associated intellectual property rights. You may not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Services or Application. You may not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Services, except as expressly permitted in the Terms. Any feedback, comments and suggestions you may provide for improvements to the Services or Applications ("Feedback") will be the sole and exclusive property of RAYVR and you hereby irrevocably assign to RAYVR all of your right, title, and interest in and to all Feedback.</p><br>
<p class="h5">Disclaimers</p>
<p>Your use of the Program is at your sole discretion and risk. We will not be responsible for any harm to your computer or mobile device, loss of data, personal injury, property damage, or other harm that results from your use of the Services and/or Application. We do not make any warranties: (i) regarding the security, accuracy, reliability, timeliness and performance of the Services; or (ii) that the Services and/or Applications will be error­free or that any errors will be corrected. RAYVR will not be liable, and you are solely responsible, for any access or usage charges charged by your wireless carrier related to any device that you use to access or use the Application or Services.</p><br>
<p>We are not responsible for (i) incorrect or inaccurate transcription of information, (ii) problems related to any of the equipment or software associated with the Services or Application or used by you, (iii) human error outside our reasonable control, (iv) any interruption, deletion, omission, degradation, defect, or line failure of any telephone network or electronic transmission, or (v) problems relating to inability to access an Application or the Services.</p><br>
<p>We disclaim all liability for any technical failures or errors of, on, or connected to the Services and/or Application, including but not limited to Push Messages sent erroneously due to technical failures or errors. We will use reasonable efforts to correct any such failures swiftly upon discovering them or being informed about them. If you think you have received Push Messages in error or experienced other technical failures, please contact us immediately.</p><br>
<p>The Services and Application, and all materials, information, products and services included therein, are provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind. WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, EXPRESS, IMPLIED OR STATUTORY, RELATING TO THE SERVICES AND APPLICATIONS, INCLUDING WITHOUT LIMITATION THE WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON­INFRINGEMENT OF PROPRIETARY RIGHTS, COURSE OF DEALING OR COURSE OF PERFORMANCE. No advice or information, whether oral or written, obtained by you from RAYVR, will create any warranty not expressly stated in this Agreement.</p><br>
<p class="h5">Indemnity</p>
<p>You agree to defend, indemnify, and hold RAYVR, its officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including without limitation reasonable attorney's fees and costs, arising out of or in any way connected with (i) your access to or use of the Application or Services; (ii) your violation of the Terms, including without limitation any representations made herein; or (iii) your violation of any third party right, including without limitation any intellectual property right, or publicity, confidentiality, property or privacy right.</p><br>
<p class="h5">Limitation of Liability</p>
<p>IN NO EVENT WILL RAYVR, ITS OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS, BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICES AND/OR APPLICATION, WHETHER THE DAMAGES ARE FORESEEABLE AND WHETHER OR NOT RAYVR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL RAYVR'S CUMULATIVE LIABILITY TO YOU, FOR ALL CLAIMS REGARDLESS OF TYPE, EXCEED TWENTY DOLLARS ($20). In addition, from time to time, various entities may sponsor reward points, offers and other rewards as part of a Service ("Sponsors"). YOU HEREBY WAIVE AND DISCLAIM ANY AND ALL LIABILITY CLAIMS AGAINST SPONSORS RELATING IN ANY WAY TO YOUR USE OF THE SERVICES OR ANY SUCH REWARDS. You agree that Sponsors are third party beneficiaries of the Terms, and may enforce its provisions directly.</p><br>
<p class="h5">Exclusions</p>
<p>Some jurisdictions do not allow the exclusion of certain warranties or the exclusion or limitation of liability for consequential or incidental damages, so the above limitation may not apply to you.</p><br>
<p class="h5">General</p>
<p>The Terms shall be governed by Florida law, without respect to its conflict of laws principles. Any dispute arising from or relating to this Agreement will be finally settled by arbitration in Palm Beach County, Florida, in accordance with the Arbitration Rules and Procedures of Judicial Arbitration and Mediation Services, Inc. ("JAMS") then in effect. The prevailing party in any arbitration or other proceeding arising under the Terms will be entitled to receive reimbursement of its reasonable expenses and attorneys' fees. Judgment may be entered in any court having jurisdiction. Notwithstanding the foregoing, we have the right to institute an action in a court of proper jurisdiction for injunctive or other equitable relief pending a final decision by the arbitrator.</p><br>
<p>The Terms are the entire agreement between you and RAYVR concerning the Program, and supersede all prior or contemporaneous communications between you and RAYVR with respect to the Program. If any provision of the Terms is deemed invalid by a court of competent jurisdiction, the remaining provisions will remain in full force and effect. No waiver of any term of the Terms shall be deemed a further or continuing waiver of such term or any other term, and RAYVR's failure to assert any right or provision under the Terms shall not constitute a waiver of such right or provision.</p><br>
<p>We reserve the right, in our sole discretion, to modify, discontinue or terminate any or all of the Program at any time, or modify the Terms without notice; updates will be posted at {{ HTML::link('https://rayvr.com/resources/terms-and-conditions', 'https://rayvr.com/resources/terms-and-conditions') }} and/or {{ HTML::link('https://rayvr.com/resources/privacy', 'https://rayvr.com/resources/privacy') }}. All modified terms and conditions will be immediately effective as of the date the modified Terms are posted on the RAYVR website and will apply to all Accounts and Members enrolled in the Program. If any modified terms and conditions are not acceptable to you, your sole remedy is to cease using the Services, and if applicable, terminate or cancel your Account. By continuing to access or use the Application and/or the Services after we have posted the new terms and conditions on the site, you agree to be bound by such changes. Members will be notified by email or in the Application or through other available means if the Program is suspended or cancelled. Notice of cancellation will also appear on the RAYVR website. If you have any questions about the Terms, please contact us at support@RAYVR.com.</p><br>
<p>We hope you will enjoy RAYVR's Program.</p><br>
<p>Last updated as of: July 1, 2014</p>
@stop